package datastruct

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"reflect"
	"sort"
	"time"
)

// Generator produces Update and Get methods for model structs via reflection.
type Generator struct {
	packageName      string
	datastructImport string
	entries          []generatorEntry
	getterEntries    []getterEntry
	needsDatastruct  bool
	externalImports  map[string]string // pkgPath -> package name
}

type generatorEntry struct {
	typeName string
	fields   []generatorField
}

type generatorField struct {
	name     string
	kind     generatorFieldKind
	typeName string
}

type generatorFieldKind int

const (
	generatorFieldKindSimplePointer generatorFieldKind = iota
	generatorFieldKindStructPointer
	generatorFieldKindMapPointer
)

type getterEntry struct {
	typeName     string
	localPkgPath string
	fields       []getterField
}

type getterField struct {
	name       string
	returnType string
	zeroValue  string
}

var timeType = reflect.TypeOf(time.Time{})

// NewGenerator creates a code generator that produces Update methods in the
// given package. The datastructImport is the import path for the datastruct
// package (used when map-merge logic is needed).
func NewGenerator(packageName string, datastructImport string) *Generator {
	return &Generator{
		packageName:      packageName,
		datastructImport: datastructImport,
	}
}

// GenerateUpdate registers a struct type for Update method generation. Pass a
// pointer to a zero value, e.g. GenerateUpdate(new(MyStruct)).
func (self *Generator) GenerateUpdate(value interface{}) {
	typ := reflect.TypeOf(value)
	if typ.Kind() == reflect.Ptr {
		typ = typ.Elem()
	}
	if typ.Kind() != reflect.Struct {
		panic(fmt.Sprintf("GenerateUpdate: expected struct, got %s", typ.Kind()))
	}

	entry := generatorEntry{
		typeName: typ.Name(),
	}

	for index := 0; index < typ.NumField(); index++ {
		field := typ.Field(index)
		if field.Type.Kind() != reflect.Ptr {
			continue
		}

		elementType := field.Type.Elem()
		generatedField := generatorField{
			name: field.Name,
		}

		switch {
		case elementType == timeType:
			generatedField.kind = generatorFieldKindSimplePointer
		case elementType.Kind() == reflect.Struct:
			generatedField.kind = generatorFieldKindStructPointer
			generatedField.typeName = elementType.Name()
		case elementType.Kind() == reflect.Map &&
			elementType.Key().Kind() == reflect.String &&
			elementType.Elem().Kind() == reflect.Interface:
			generatedField.kind = generatorFieldKindMapPointer
			self.needsDatastruct = true
		default:
			generatedField.kind = generatorFieldKindSimplePointer
		}

		entry.fields = append(entry.fields, generatedField)
	}

	self.entries = append(self.entries, entry)
}

// GenerateGetters registers a struct type for getter method generation. For
// each pointer field, a Get<FieldName>() method is generated that returns the
// dereferenced value or the zero value when the pointer is nil. Pass a pointer
// to a zero value, e.g. GenerateGetters(new(MyStruct)).
func (self *Generator) GenerateGetters(value interface{}) {
	typ := reflect.TypeOf(value)
	if typ.Kind() == reflect.Ptr {
		typ = typ.Elem()
	}
	if typ.Kind() != reflect.Struct {
		panic(fmt.Sprintf("GenerateGetters: expected struct, got %s", typ.Kind()))
	}

	localPkgPath := typ.PkgPath()
	entry := getterEntry{
		typeName:     typ.Name(),
		localPkgPath: localPkgPath,
	}

	for index := 0; index < typ.NumField(); index++ {
		field := typ.Field(index)
		if field.Type.Kind() != reflect.Ptr {
			continue
		}

		elementType := field.Type.Elem()

		self.collectExternalImports(elementType, localPkgPath)

		entry.fields = append(entry.fields, getterField{
			name:       field.Name,
			returnType: reflectTypeToString(elementType, localPkgPath),
			zeroValue:  reflectTypeToZeroValue(elementType, localPkgPath),
		})
	}

	self.getterEntries = append(self.getterEntries, entry)
}

// collectExternalImports records the import path for any named type that lives
// outside localPkgPath. It recurses into slice/map/pointer element types.
func (self *Generator) collectExternalImports(target reflect.Type, localPkgPath string) {
	if target.Name() != "" && target.PkgPath() != "" && target.PkgPath() != localPkgPath {
		if self.externalImports == nil {
			self.externalImports = map[string]string{}
		}
		self.externalImports[target.PkgPath()] = target.Name()
	}
	switch target.Kind() {
	case reflect.Slice, reflect.Ptr:
		self.collectExternalImports(target.Elem(), localPkgPath)
	case reflect.Map:
		self.collectExternalImports(target.Key(), localPkgPath)
		self.collectExternalImports(target.Elem(), localPkgPath)
	}
}

// MustWriteFile formats and writes the generated code to filename. It panics
// on any error.
func (self *Generator) MustWriteFile(filename string) {
	var buffer bytes.Buffer

	buffer.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buffer, "package %s\n\n", self.packageName)

	var imports []string
	for pkgPath := range self.externalImports {
		imports = append(imports, fmt.Sprintf(`"%s"`, pkgPath))
	}
	if self.needsDatastruct {
		imports = append(imports, fmt.Sprintf(`"%s"`, self.datastructImport))
	}
	sort.Strings(imports)
	switch len(imports) {
	case 1:
		fmt.Fprintf(&buffer, "import %s\n\n", imports[0])
	default:
		if len(imports) > 1 {
			buffer.WriteString("import (\n")
			for _, importPath := range imports {
				fmt.Fprintf(&buffer, "\t%s\n", importPath)
			}
			buffer.WriteString(")\n\n")
		}
	}

	for _, entry := range self.entries {
		self.writeUpdateMethod(&buffer, entry)
	}

	for _, entry := range self.getterEntries {
		self.writeGetterMethods(&buffer, entry)
	}

	formatted, formatError := format.Source(buffer.Bytes())
	if formatError != nil {
		fmt.Fprintf(os.Stderr, "generated code:\n%s\n", buffer.String())
		panic(fmt.Sprintf("failed to format generated code: %v", formatError))
	}

	if writeError := os.WriteFile(filename, formatted, 0644); writeError != nil {
		panic(fmt.Sprintf("failed to write file %s: %v", filename, writeError))
	}
}

func (self *Generator) writeUpdateMethod(buffer *bytes.Buffer, entry generatorEntry) {
	fmt.Fprintf(buffer, "func (self *%s) Update(data *%s) {\n", entry.typeName, entry.typeName)
	buffer.WriteString("\tif data == nil {\n\t\treturn\n\t}\n")

	for _, field := range entry.fields {
		switch field.kind {
		case generatorFieldKindSimplePointer:
			fmt.Fprintf(buffer, "\tif data.%s != nil {\n", field.name)
			fmt.Fprintf(buffer, "\t\tself.%s = data.%s\n", field.name, field.name)
			buffer.WriteString("\t}\n")

		case generatorFieldKindStructPointer:
			fmt.Fprintf(buffer, "\tif data.%s != nil {\n", field.name)
			fmt.Fprintf(buffer, "\t\tif self.%s == nil {\n", field.name)
			fmt.Fprintf(buffer, "\t\t\tself.%s = new(%s)\n", field.name, field.typeName)
			buffer.WriteString("\t\t}\n")
			fmt.Fprintf(buffer, "\t\tself.%s.Update(data.%s)\n", field.name, field.name)
			buffer.WriteString("\t}\n")

		case generatorFieldKindMapPointer:
			fmt.Fprintf(buffer, "\tif data.%s != nil {\n", field.name)
			fmt.Fprintf(buffer, "\t\tif self.%s == nil {\n", field.name)
			fmt.Fprintf(buffer, "\t\tself.%s = data.%s\n", field.name, field.name)
			buffer.WriteString("\t\t} else {\n")
			fmt.Fprintf(buffer, "\t\t\tmerged := datastruct.UpdateMap(*self.%s, *data.%s)\n", field.name, field.name)
			fmt.Fprintf(buffer, "\t\t\tself.%s = &merged\n", field.name)
			buffer.WriteString("\t\t}\n")
			buffer.WriteString("\t}\n")
		}
	}

	buffer.WriteString("}\n\n")
}

func (self *Generator) writeGetterMethods(buffer *bytes.Buffer, entry getterEntry) {
	for _, field := range entry.fields {
		fmt.Fprintf(buffer, "func (self *%s) Get%s() %s {\n", entry.typeName, field.name, field.returnType)
		fmt.Fprintf(buffer, "\tif self.%s != nil {\n", field.name)
		fmt.Fprintf(buffer, "\t\treturn *self.%s\n", field.name)
		buffer.WriteString("\t}\n")
		fmt.Fprintf(buffer, "\treturn %s\n", field.zeroValue)
		buffer.WriteString("}\n\n")
	}
}

// reflectTypeToString returns the Go source representation of a reflect.Type.
// Types from localPkgPath are emitted unqualified; external types are
// package-qualified (e.g. "time.Time").
func reflectTypeToString(target reflect.Type, localPkgPath string) string {
	if target.Name() != "" {
		if target.PkgPath() == "" {
			if target.Name() == "uint8" {
				return "byte"
			}
			return target.Name()
		}
		if target.PkgPath() == localPkgPath {
			return target.Name()
		}
		return target.String()
	}

	switch target.Kind() {
	case reflect.Slice:
		return "[]" + reflectTypeToString(target.Elem(), localPkgPath)
	case reflect.Map:
		return "map[" + reflectTypeToString(target.Key(), localPkgPath) + "]" + reflectTypeToString(target.Elem(), localPkgPath)
	case reflect.Ptr:
		return "*" + reflectTypeToString(target.Elem(), localPkgPath)
	case reflect.Interface:
		if target.NumMethod() == 0 {
			return "interface{}"
		}
		return target.String()
	default:
		return target.String()
	}
}

// reflectTypeToZeroValue returns the Go source literal for the zero value of a
// reflect.Type. Primitives and named-primitive types get their typed zero
// ("", false, 0); slices, maps, pointers and interfaces get nil; structs get
// TypeName{}.
func reflectTypeToZeroValue(target reflect.Type, localPkgPath string) string {
	switch target.Kind() {
	case reflect.String:
		return `""`
	case reflect.Bool:
		return "false"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return "0"
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return "0"
	case reflect.Float32, reflect.Float64:
		return "0"
	case reflect.Slice, reflect.Map, reflect.Ptr, reflect.Interface:
		return "nil"
	case reflect.Struct:
		return reflectTypeToString(target, localPkgPath) + "{}"
	default:
		return reflectTypeToString(target, localPkgPath) + "{}"
	}
}
