run:
  timeout: 5m

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

output:
  formats:
    - format: colored-line-number
  sort-results: true
