ALTER TABLE tokens ADD COLUMN IF NOT EXISTS remote_address VARCHAR(128) NULL;
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS user_agent VARCHAR(256) NULL;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ NULL;
